### ISSUE TITLE
Please depend on igraph instead of python-igraph

### ISSUE THREAD

**Issue by szhorvat** [SUwonglab/arcsv#11]
Please consider depending on `igraph` instead of `python-igraph`. The latter name has been deprecated for nearly two years on PyPI and will soon stop receiving updates. See https://github.com/igraph/python-igraph/issues/699 for details.

Ref: https://github.com/search?q=repo%3ASUwonglab%2Farcsv%20python-igraph&type=code

**Comment by jgarthur** [comment]
done, thank you! https://github.com/SUwonglab/arcsv/pull/12
