### ISSUE TITLE
Can arcsv genotype samples using a ref complex-SV vcf files

### ISSUE THREAD

**Issue by songtaogui** [SUwonglab/arcsv#2]
Hi,

Thank you for developing this wonderful tool.

I have learned that arcsv can call complex-SVs in each sample. I was wondering that is it possible that I merge all sample's complex-SV calls into one file, and use the merged SVs to genotype all the samples? Or if I identified some complex-SVs by comparing two genomes, could I use arcsv to genotype these SVs in population samples?

Thank you

Best wishes, 
Songtao Gui

**Comment by jgarthur** [comment]
Thanks for the feedback! To answer your questions:

1) I have observed many SVs called identically in multiple samples, so a simple de-duplication step may be sufficient here. Merging different SVs into a common one is a tricky problem, however -- even for simple SVs.
2) Genotyping new samples based on an existing set of complex SVs (from ARC-SV or somewhere else) is not possible, unfortunately. ARC-SV is actually very well-suited to this task, so some genotyping-only mode may be added in the future.

**Comment by songtaogui** [comment]
Dear Joey,

Thank you for you reply.

I will try merging each sample's SV .

Best wishes,

Songtao Gui
