### ISSUE TITLE
arcsv container?

### ISSUE THREAD

**Issue by tmaroilley** [SUwonglab/arcsv#9]
Hi, 

I am very interested in testing arcsv as I heard about it at the ASHG2022 in LA, CA. However, I struggle at installing it on a cluster on which I do not have much support or admin rights. I was wondering if a container version of arcsv was available?

Thanks for your help, 
Best regards, 
Tatiana

**Comment by jgarthur** [comment]
I haven't personally created a container for arcsv, but for use case I would recommend trying `conda`:

https://github.com/SUwonglab/arcsv?tab=readme-ov-file#example-using-conda
